### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by taipeiwu** [cipchk/ngx-countdown#10]
If I continue to open, there will be this problem, is there a good solution?

[CHROME CONSOLE LOG - 1]
```
Runtime Error
Maximum call stack size exceeded
Stack
RangeError: Maximum call stack size exceeded
    at CountdownComponent.reflow (http://localhost:8100/build/vendor.js:69415:14)
    at CountdownComponent.me.reflow (http://localhost:8100/build/vendor.js:69384:28)
    at CountdownComponent.me.reflow (http://localhost:8100/build/vendor.js:69384:28)
    at CountdownComponent.me.reflow (http://localhost:8100/build/vendor.js:69384:28)
    at CountdownComponent.me.reflow (http://localhost:8100/build/vendor.js:69384:28)
    at CountdownComponent.me.reflow (http://localhost:8100/build/vendor.js:69384:28)
    at CountdownComponent.me.reflow (http://localhost:8100/build/vendor.js:69384:28)
    at CountdownComponent.me.reflow (http://localhost:8100/build/vendor.js:69384:28)
    at CountdownComponent.me.reflow (http://localhost:8100/build/vendor.js:69384:28)
    at CountdownComponent.me.reflow (http://localhost:8100/build/vendor.js:69384:28)
```
[vendor.js:69415:14] ( 69415 => function (count, force) { )
```
    /**
     * 更新时钟
     */
    /**
         * 更新时钟
         */
    CountdownComponent.prototype.reflow = /**
         * 更新时钟
         */
    function (count, force) {
        if (count === void 0) { count = 0; }
        if (force === void 0) { force = false; }
        if (!force && (this.parsed || this.stoped))
            return;
        var me = this;
        me.left = me.left - me.frequency * count;
        me.hands.forEach(function (hand) {
            hand.lastValue = hand.value;
            hand.value = Math.floor(me.left / hand.base) % hand.radix;
        });
        me.repaint();
        if (me._notify[me.left]) {
            me.notify.emit(me.left);
            this.callEvent('notify');
        }
        if (me.left < 1) {
            me.finished.emit(0);
            this.stoped = true;
            this.callEvent('finished');
            this.destroy();
        }
    };
```

[vendor.js:69384:28] ( 69384 => return _reflow.apply(me, [count]); )
```
    CountdownComponent.prototype.init = function () {
        var me = this;
        var el = me.el.nativeElement;
        me.parsed = me.config.demand;
        me.stoped = false;
        this.cls = "count-down " + me.config.size + " " + (me.config.className || '');
        // 分析markup
        var tmpl = el.innerHTML || me.config.template;
        me.config.varRegular.lastIndex = 0;
        el.innerHTML = tmpl.replace(me.config.varRegular, function (str, type) {
            // 时钟频率校正.
            if (type === 'u' || type === 's-ext')
                me.frequency = 100;
            // 生成hand的markup
            var content = '';
            if (type === 's-ext') {
                me.hands.push({ type: 's' });
                me.hands.push({ type: 'u' });
                content = me.html('', 's', 'handlet') +
                    me.html('.', '', 'digital') +
                    me.html('', 'u', 'handlet');
            }
            else {
                me.hands.push({ type: type });
            }
            return me.html(content, type, 'hand');
        });
        var clock = me.config.clock;
        me.hands.forEach(function (hand) {
            var type = hand.type;
            var base = 100, i;
            hand.node = el.querySelector(".hand-" + type);
            // radix, bits 初始化
            for (i = clock.length - 3; i > -1; i -= 3) {
                if (type === clock[i]) {
                    break;
                }
                base *= clock[i + 1];
            }
            hand.base = base;
            hand.radix = clock[i + 1];
            hand.bits = clock[i + 2];
        });
        me.getLeft();
        me.reflow(0, true);
        // bind reflow to me
        var _reflow = me.reflow;
        me.reflow = function (count) {
            if (count === void 0) { count = 0; }
            return _reflow.apply(me, [count]);
        };
        // 构建 notify
        if (me.config.notify) {
            me.config.notify.forEach(function (time) {
                if (time < 1)
                    throw new Error('由于当结束会调用 finished，所以 notify 通知必须全是正整数');
                time = time * 1000;
                time = time - time % me.frequency;
                me._notify[time] = true;
            });
        }
        me.start.emit();
        me.timer.add(me.reflow, me.frequency);
        // show
        el.style.display = 'inline';
        return me;
    };
```

```
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.7
Angular Core: ^5.1.3
Angular Compiler CLI: ^5.1.3
Node: 8.9.2
OS Platform: Windows 7
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
```

--- Update 2018/01/20 ---
[CHROME CONSOLE LOG - 2]
```
ERROR RangeError: Maximum call stack size exceeded
    at CountdownComponent.html (vendor.js:69489)
    at vendor.js:69458
    at Array.forEach (<anonymous>)
    at vendor.js:69457
    at Array.forEach (<anonymous>)
    at CountdownComponent.repaint (vendor.js:69454)
    at CountdownComponent.reflow (vendor.js:69426)
    at CountdownComponent.me.reflow (vendor.js:69384)
    at CountdownComponent.me.reflow (vendor.js:69384)
    at CountdownComponent.me.reflow (vendor.js:69384)
```

[vendor.js:69489] ( 69489 => function (con, className, type) { )
```
    /**
     * 生成需要的html代码，辅助工具
     */
    /**
         * 生成需要的html代码，辅助工具
         */
    CountdownComponent.prototype.html = /**
         * 生成需要的html代码，辅助工具
         */
    function (con, className, type) {
        if (con instanceof Array) {
            con = con.join('');
        }
        switch (type) {
            case 'hand':
            case 'handlet':
                className = type + ' hand-' + className;
                break;
            case 'digital':
                if (con === '.') {
                    className = type + ' ' + type + '-point ' + className;
                }
                else {
                    className = type + ' ' + type + '-' + con + ' ' + className;
                }
                break;
        }
        return '<span class="' + className + '">' + con + '</span>';
    };
```

[vendor.js:69458] ( 69458 => content += me.html(digital.toString(), '', 'digital'); )
```
    /**
     * 重绘时钟
     */
    /**
         * 重绘时钟
         */
    CountdownComponent.prototype.repaint = /**
         * 重绘时钟
         */
    function () {
        var me = this;
        if (me.config.repaint) {
            me.config.repaint.apply(me);
            return;
        }
        var content;
        me.hands.forEach(function (hand) {
            if (hand.lastValue !== hand.value) {
                content = '';
                me.toDigitals(hand.value, hand.bits).forEach(function (digital) {
                    content += me.html(digital.toString(), '', 'digital');
                });
                hand.node.innerHTML = content;
            }
        });
    };
```

[vendor.js:69454] ( 69454=> me.hands.forEach(function (hand) { )
```
    /**
     * 重绘时钟
     */
    /**
         * 重绘时钟
         */
    CountdownComponent.prototype.repaint = /**
         * 重绘时钟
         */
    function () {
        var me = this;
        if (me.config.repaint) {
            me.config.repaint.apply(me);
            return;
        }
        var content;
        me.hands.forEach(function (hand) {
            if (hand.lastValue !== hand.value) {
                content = '';
                me.toDigitals(hand.value, hand.bits).forEach(function (digital) {
                    content += me.html(digital.toString(), '', 'digital');
                });
                hand.node.innerHTML = content;
            }
        });
    };
```

[vendor.js:69426] ( 69426=> me.repaint(); )
```
    /**
     * 更新时钟
     */
    /**
         * 更新时钟
         */
    CountdownComponent.prototype.reflow = /**
         * 更新时钟
         */
    function (count, force) {
        if (count === void 0) { count = 0; }
        if (force === void 0) { force = false; }
        if (!force && (this.parsed || this.stoped))
            return;
        var me = this;
        me.left = me.left - me.frequency * count;
        me.hands.forEach(function (hand) {
            hand.lastValue = hand.value;
            hand.value = Math.floor(me.left / hand.base) % hand.radix;
        });
        me.repaint();
        if (me._notify[me.left]) {
            me.notify.emit(me.left);
            this.callEvent('notify');
        }
        if (me.left < 1) {
            me.finished.emit(0);
            this.stoped = true;
            this.callEvent('finished');
            this.destroy();
        }
    };
```

**Comment by taipeiwu** [comment]
Hi, is there any update on this issue? @cipchk

**Comment by cipchk** [comment]
Sorry, can you provider a online demo for your ENV via [stackblitz](https://stackblitz.com/edit/ngx-countdown-setup?file=app%2Fapp.component.ts).

**Comment by taipeiwu** [comment]
Because that architecture is IONIC,
it's a bit hard to port completely to stackblitz,
so I'm still confirming the reason,
and I'll let you know more clearly.
